
-- Enable RLS on all tables
ALTER TABLE public.bar_close_summaries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bar_item_dispatch_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bar_item_shot_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bars ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.business_profile ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.guestlist ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.nights ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.placements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.po_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pos_bar_mappings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pos_bar_product_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pos_bar_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pos_connections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pos_product_item_mappings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pos_source_map ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pos_sync_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pos_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.purchase_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.receipt_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.receipts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.recipe_ingredients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.recipes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.staff ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.suppliers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.venues ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vip_tables ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.warehouse_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.warehouse_transfers ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "admin_all" ON public.bar_close_summaries FOR ALL TO public USING ((auth.role() = 'authenticated'::text));
CREATE POLICY "bcs_auth_full" ON public.bar_close_summaries FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "admin_all" ON public.bar_item_dispatch_snapshots FOR ALL TO public USING ((auth.role() = 'authenticated'::text));
CREATE POLICY "bids_auth_full" ON public.bar_item_dispatch_snapshots FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "admin_all" ON public.bar_item_shot_snapshots FOR ALL TO public USING ((auth.role() = 'authenticated'::text));
CREATE POLICY "biss_auth_full" ON public.bar_item_shot_snapshots FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "bars_admin" ON public.bars FOR ALL TO public USING ((auth.role() = 'authenticated'::text));
CREATE POLICY "bars_read_anon" ON public.bars FOR SELECT TO public USING (true);
CREATE POLICY "admin_all" ON public.business_profile FOR ALL TO public USING ((auth.role() = 'authenticated'::text));
CREATE POLICY "anon_read" ON public.business_profile FOR SELECT TO public USING (true);
CREATE POLICY "events_delete_auth" ON public.events FOR DELETE TO public USING ((auth.role() = 'authenticated'::text));
CREATE POLICY "events_insert_anon" ON public.events FOR INSERT TO public WITH CHECK (true);
CREATE POLICY "events_read_all" ON public.events FOR SELECT TO public USING (true);
CREATE POLICY "events_update_auth" ON public.events FOR UPDATE TO public USING ((auth.role() = 'authenticated'::text));
CREATE POLICY "admin_all" ON public.guestlist FOR ALL TO public USING ((auth.role() = 'authenticated'::text));
CREATE POLICY "admin_all" ON public.invoices FOR ALL TO public USING ((auth.role() = 'authenticated'::text));
CREATE POLICY "items_admin" ON public.items FOR ALL TO public USING ((auth.role() = 'authenticated'::text));
CREATE POLICY "items_read_anon" ON public.items FOR SELECT TO public USING (true);
CREATE POLICY "nights_admin" ON public.nights FOR ALL TO public USING ((auth.role() = 'authenticated'::text));
CREATE POLICY "nights_read_anon" ON public.nights FOR SELECT TO public USING (true);
CREATE POLICY "placements_admin" ON public.placements FOR ALL TO public USING ((auth.role() = 'authenticated'::text));
CREATE POLICY "placements_read_anon" ON public.placements FOR SELECT TO public USING (true);
CREATE POLICY "admin_all" ON public.po_items FOR ALL TO public USING ((auth.role() = 'authenticated'::text));
CREATE POLICY "admin_all" ON public.pos_bar_mappings FOR ALL TO public USING ((auth.role() = 'authenticated'::text));
CREATE POLICY "auth_full_pos_bar_mappings" ON public.pos_bar_mappings FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "admin_all" ON public.pos_bar_product_snapshots FOR ALL TO public USING ((auth.role() = 'authenticated'::text));
CREATE POLICY "auth_full_pos_bar_product_snapshots" ON public.pos_bar_product_snapshots FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "admin_all" ON public.pos_bar_snapshots FOR ALL TO public USING ((auth.role() = 'authenticated'::text));
CREATE POLICY "auth_full_pos_bar_snapshots" ON public.pos_bar_snapshots FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "admin_all" ON public.pos_connections FOR ALL TO public USING ((auth.role() = 'authenticated'::text));
CREATE POLICY "admin_all" ON public.pos_product_item_mappings FOR ALL TO public USING ((auth.role() = 'authenticated'::text));
CREATE POLICY "pos_source_map_auth_rw" ON public.pos_source_map FOR ALL TO public USING ((auth.role() = 'authenticated'::text));
CREATE POLICY "admin_all" ON public.pos_sync_runs FOR ALL TO public USING ((auth.role() = 'authenticated'::text));
CREATE POLICY "pos_transactions_auth_rw" ON public.pos_transactions FOR ALL TO public USING ((auth.role() = 'authenticated'::text));
CREATE POLICY "profiles_own" ON public.profiles FOR SELECT TO authenticated USING ((auth.uid() = id));
CREATE POLICY "admin_all" ON public.purchase_orders FOR ALL TO public USING ((auth.role() = 'authenticated'::text));
CREATE POLICY "admin_all" ON public.receipt_items FOR ALL TO public USING ((auth.role() = 'authenticated'::text));
CREATE POLICY "ri_auth_full" ON public.receipt_items FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "admin_all" ON public.receipts FOR ALL TO public USING ((auth.role() = 'authenticated'::text));
CREATE POLICY "receipts_auth_full" ON public.receipts FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "admin_all" ON public.recipe_ingredients FOR ALL TO public USING ((auth.role() = 'authenticated'::text));
CREATE POLICY "admin_all" ON public.recipes FOR ALL TO public USING ((auth.role() = 'authenticated'::text));
CREATE POLICY "staff_admin" ON public.staff FOR ALL TO public USING ((auth.role() = 'authenticated'::text));
CREATE POLICY "staff_read_anon" ON public.staff FOR SELECT TO public USING (true);
CREATE POLICY "stations_admin" ON public.stations FOR ALL TO public USING ((auth.role() = 'authenticated'::text));
CREATE POLICY "stations_read_anon" ON public.stations FOR SELECT TO public USING (true);
CREATE POLICY "admin_all" ON public.suppliers FOR ALL TO public USING ((auth.role() = 'authenticated'::text));
CREATE POLICY "venues_anon_read" ON public.venues FOR SELECT TO anon USING (true);
CREATE POLICY "venues_auth" ON public.venues FOR ALL TO public USING ((auth.role() = 'authenticated'::text));
CREATE POLICY "venues_auth_full" ON public.venues FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "admin_all" ON public.vip_tables FOR ALL TO public USING ((auth.role() = 'authenticated'::text));
CREATE POLICY "admin_all" ON public.warehouse_items FOR ALL TO public USING ((auth.role() = 'authenticated'::text));
CREATE POLICY "admin_all" ON public.warehouse_transfers FOR ALL TO public USING ((auth.role() = 'authenticated'::text));
CREATE POLICY "wt_auth_full" ON public.warehouse_transfers FOR ALL TO authenticated USING (true) WITH CHECK (true);
;
